# Generated by Django 4.2.27 on 2026-01-19 15:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChinaDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Doctor's full name (in English or pinyin)", max_length=200)),
                ('hospital', models.CharField(help_text='Hospital name (e.g., Peking Union Medical College Hospital)', max_length=300)),
                ('department', models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('oncology', 'Oncology'), ('gastroenterology', 'Gastroenterology'), ('endocrinology', 'Endocrinology'), ('dermatology', 'Dermatology'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT (Ear, Nose, Throat)'), ('general', 'General Medicine'), ('other', 'Other')], help_text='Medical department/specialty', max_length=50)),
                ('biography_en', models.TextField(help_text="Doctor's biography in English including qualifications, experience, and expertise")),
                ('is_available', models.BooleanField(default=True, help_text='Whether the doctor is currently accepting consultations')),
                ('years_of_experience', models.PositiveIntegerField(default=0, help_text='Years of medical practice experience')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'China Doctor',
                'verbose_name_plural': 'China Doctors',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='North American phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('language_preference', models.CharField(choices=[('en', 'English'), ('zh-cn', 'Chinese (Simplified)'), ('zh-tw', 'Chinese (Traditional)')], default='en', help_text='Preferred language for communication', max_length=10)),
                ('medical_history', models.TextField(blank=True, help_text='Basic medical history, allergies, current medications, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms_description', models.TextField(help_text='Detailed description of symptoms provided by the user')),
                ('ai_suggestion', models.JSONField(blank=True, help_text='AI-generated triage analysis and department suggestion', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the consultation', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Scheduled date and time for the consultation', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments about the consultation')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the consultation request was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('doctor', models.ForeignKey(help_text='Doctor assigned to the consultation', on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='med_services.chinadoctor')),
                ('user_profile', models.ForeignKey(help_text='User requesting the consultation', on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='med_services.userprofile')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-created_at'],
            },
        ),
    ]
