# Generated by Django 4.2.27 on 2026-01-20 13:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='report_file',
            field=models.FileField(blank=True, help_text='Optional medical report (PDF or image)', null=True, upload_to='reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Availability date')),
                ('start_time', models.TimeField(help_text='Start time for availability window')),
                ('end_time', models.TimeField(help_text='End time for availability window')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(help_text='Doctor this availability belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='med_services.chinadoctor')),
            ],
            options={
                'verbose_name': 'Doctor Availability',
                'verbose_name_plural': 'Doctor Availabilities',
                'ordering': ['doctor', 'date', 'start_time'],
                'unique_together': {('doctor', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
