# Generated by Django 4.2.27 on 2026-01-20 13:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med_services', '0002_consultation_report_file_doctoravailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(help_text='Rating stars (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Optional review comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.OneToOneField(help_text='The consultation this review belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='med_services.consultation')),
            ],
            options={
                'verbose_name': 'Doctor Review',
                'verbose_name_plural': 'Doctor Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
